server:
  servlet:
    context-path: /storage

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 6000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 6000
#        minEvictableIdleTimeMillis: 30000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    application:
      name: storage
#    freemarker:
#      template-loader-path: classpath:/templates
#      cache: false
#      charset: UTF-8
#      check-template-location: true
#      content-type: text/html
#      expose-request-attributes: true
#      expose-session-attributes: true
#      request-context-attribute: request
#      suffix: .ftl

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.huafengodel

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql